### PR TITLE
Add quill switch problem and solution

### PR DESCRIPTION
**Pull request by kelteseth**
This was really annoying but a simple container restart fixed the problem. If I only knew this earlier...

### CODE REVIEW

**Comment by nilsramsperger** [comment]
I wonder how the problem did arise. If I understand it right, you tried to update the container after the problem occurred. Didn't you have to rebuild and restart your fork for that anyway?

**Comment by kelteseth** [comment]
What I did:

1. Connect to the vserver
2. sudo apt update && apt upgrade
3. Update nodebb https://gitlab.com/kelteseth/ScreenPlayProject#update-nodebb
4. Restart rebuild nodebb
5. Writing and reply was broken. Disable the old editor (multiple rebuild) did not help
6. Downgrade to 1.15.5 did not help
7. Restart the base vserver then starting 1.16 worked

**Comment by nilsramsperger** [comment]
So in the end, it's not quite clear which of the steps caused the problem:
- updating the server
- updating the container
- installing the plugin

Interesting situation. I'm going to merge the change and add some further context to it.

**Comment by nilsramsperger** [comment]
Pushed the extended FAQ entry. What do you think?

**Comment by kelteseth** [comment]
@nilsramsperger LGTM👏

**Pull request merged**
